import os, random, re, ast, time, json, hashlib, subprocess

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AUTO_ECHO = os.path.join(BASE, 'auto-echo.py')
GENOME_FILE = os.path.join(BASE, 'genome.json')
REWRITE_LOG = os.path.join(BASE, 'clockwork_rewrite_log.jsonl')

SELF_REWRITE_CADENCE_DEFAULT = 2
REWRITE_MIN_INTERVAL = 1
REWRITE_MAX_INTERVAL = 6

def _load_source_hash():
    try:
        with open(AUTO_ECHO) as f:
            return hashlib.sha256(f.read().encode()).hexdigest()[:16]
    except:
        return None

def _file_line_count(fpath):
    try:
        with open(fpath) as f:
            return sum(1 for _ in f)
    except:
        return 0

def _git_diff_stat():
    try:
        r = subprocess.run(
            ['git', 'diff', '--shortstat', 'HEAD', '--', 'auto-echo.py'],
            cwd=BASE, capture_output=True, text=True, timeout=5
        )
        return r.stdout.strip()
    except:
        return ""

def _record_rewrite(genome, event, detail):
    gen = genome.get('generation', 0)
    entry = json.dumps({
        'gen': gen,
        'time': time.time(),
        'event': event,
        'detail': detail,
        'source_hash': _load_source_hash(),
        'lines': _file_line_count(AUTO_ECHO),
    })
    with open(REWRITE_LOG, 'a') as f:
        f.write(entry + '\n')

def _read_rewrite_log():
    if not os.path.exists(REWRITE_LOG):
        return []
    entries = []
    with open(REWRITE_LOG) as f:
        for line in f:
            if line.strip():
                try:
                    entries.append(json.loads(line))
                except:
                    pass
    return entries

def _adaptive_cadence(genome):
    log = _read_rewrite_log()
    recent = [e for e in log if e.get('gen', 0) > genome.get('generation', 0) - 10]
    successes = sum(1 for e in recent if e.get('event') == 'rewrite_ok')
    attempts = sum(1 for e in recent if e.get('event') in ('rewrite_ok', 'rewrite_fail'))
    base = genome.get('rewrite_cadence', SELF_REWRITE_CADENCE_DEFAULT)
    if attempts > 0:
        success_rate = successes / attempts
        if success_rate < 0.3:
            base = min(REWRITE_MAX_INTERVAL, base + 1)
        elif success_rate > 0.7:
            base = max(REWRITE_MIN_INTERVAL, base - 1)
    genome['rewrite_cadence'] = base
    return base

def _should_rewrite(genome):
    gen = genome.get('generation', 0)
    cadence = _adaptive_cadence(genome)
    last_rewrite_gen = genome.get('last_rewrite_gen', 0)
    return (gen - last_rewrite_gen) >= cadence

def _perform_source_rewrite(genome):
    gen = genome.get('generation', 0)
    lines = _file_line_count(AUTO_ECHO)
    if lines < 10:
        return "too_few_lines"

    try:
        with open(AUTO_ECHO) as f:
            source = f.read()
    except:
        return "read_fail"

    old_hash = hashlib.sha256(source.encode()).hexdigest()[:16]
    source_lines = source.split('\n')

    strategy = random.choice([
        'inject_clock_marker',
        'add_generation_counter',
        'insert_pulse_feedback',
        'add_rewrite_cadence_awareness',
        'mutate_budget_constants',
    ])

    if strategy == 'inject_clock_marker':
        marker = f"# clock_rewrite:gen={gen}:ts={int(time.time())}:cadence={genome.get('rewrite_cadence', '?')}"
        insert_at = random.randint(0, max(len(source_lines) - 1, 0))
        source_lines.insert(insert_at, marker)

    elif strategy == 'add_generation_counter':
        func = (
            f"\ndef clockwork_generation_marker():\n"
            f"    # Auto-generated by clockwork at gen {gen}\n"
            f"    return {gen}\n"
        )
        source_lines.append(func)

    elif strategy == 'insert_pulse_feedback':
        func = (
            f"\ndef clockwork_pulse_feedback(genome):\n"
            f"    # clockwork pulse feedback @ gen {gen}\n"
            f"    pulse = genome.get('clock_pulse', 0.0)\n"
            f"    cadence = genome.get('rewrite_cadence', 2)\n"
            f"    genome['clockwork_last_pulse'] = pulse\n"
            f"    genome['clockwork_last_cadence'] = cadence\n"
            f"    return pulse * cadence\n"
        )
        source_lines.append(func)

    elif strategy == 'add_rewrite_cadence_awareness':
        idx = random.randint(0, max(len(source_lines) - 1, 0))
        source_lines.insert(
            idx,
            f"    # clockwork_cadence_aware:gen={gen}"
        )

    elif strategy == 'mutate_budget_constants':
        for i, line in enumerate(source_lines):
            if 'gen_time_budget' in line and '120' in line:
                new_val = random.choice([60, 90, 150, 180, 240])
                source_lines[i] = line.replace('120', str(new_val))
                break

    new_source = '\n'.join(source_lines)
    new_hash = hashlib.sha256(new_source.encode()).hexdigest()[:16]

    if new_hash == old_hash:
        _record_rewrite(genome, 'rewrite_noop', strategy)
        return "noop"

    try:
        with open(AUTO_ECHO, 'w') as f:
            f.write(new_source)
    except:
        return "write_fail"

    try:
        ast.parse(new_source)
    except SyntaxError:
        try:
            with open(AUTO_ECHO, 'w') as f:
                f.write(source)
        except:
            pass
        _record_rewrite(genome, 'rewrite_fail_syntax', strategy)
        return "syntax_fail"

    genome['last_rewrite_gen'] = gen
    genome['last_rewrite_hash'] = new_hash
    genome['source_rewrite_count'] = genome.get('source_rewrite_count', 0) + 1
    _record_rewrite(genome, 'rewrite_ok', strategy)

    stat = _git_diff_stat()
    if stat:
        _record_rewrite(genome, 'git_diff', stat)

    return f"ok:{strategy}:{old_hash}->{new_hash}"

def _fire_scheduled_triggers(genome, gen):
    fired = []
    triggers = genome.get('scheduled_triggers', [])
    for t in triggers:
        if t.get('gen') == gen and not t.get('fired', False):
            action = t.get('action', '')
            if action == 'force_self_rewrite':
                result = _perform_source_rewrite(genome)
                fired.append(f"trigger:force_self_rewrite={result}")
            elif action == 'boost_mutation':
                old = genome.get('mutation_rate', 0.15)
                genome['mutation_rate'] = min(0.50, old + t.get('amount', 0.05))
                fired.append(f"trigger:boost_mutation(gen={gen})")
            elif action == 'inject_noise':
                genome['selection_noise_std'] = genome.get('selection_noise_std', 0.5) + t.get('amount', 0.2)
                fired.append(f"trigger:inject_noise(gen={gen})")
            elif action == 'reset_streaks':
                for a in genome.get('agents', []):
                    a['low_score_streak'] = 0
                fired.append(f"trigger:reset_streaks(gen={gen})")
            elif action == 'self_rewrite':
                old = genome.get('mutation_rate', 0.15)
                genome['mutation_rate'] = min(0.50, old + t.get('amount', 0.1))
                genome['clock_self_rewrites'] = genome.get('clock_self_rewrites', 0) + 1
                fired.append(f"trigger:self_rewrite(gen={gen})")
            t['fired'] = True
    return fired

def _schedule_periodic_rewrites(genome, gen):
    scheduled = []
    triggers = genome.setdefault('scheduled_triggers', [])
    existing_rewrite_gens = {t.get('gen') for t in triggers if t.get('action') == 'force_self_rewrite'}
    cadence = genome.get('rewrite_cadence', SELF_REWRITE_CADENCE_DEFAULT)

    next_gen = gen + cadence
    if next_gen not in existing_rewrite_gens:
        triggers.append({
            'gen': next_gen,
            'action': 'force_self_rewrite',
            'amount': 0,
            'fired': False,
        })
        scheduled.append(f"periodic_rewrite@{next_gen}")

    for offset in range(1, cadence + 1):
        future = gen + offset
        if future not in existing_rewrite_gens and random.random() < 0.3:
            actions = ['boost_mutation', 'inject_noise', 'reset_streaks']
            triggers.append({
                'gen': future,
                'action': random.choice(actions),
                'amount': round(random.uniform(0.02, 0.1), 3),
                'fired': False,
            })
            scheduled.append(f"{actions[-1]}@{future}")

    return scheduled

def _clock_emergency_rewrite(genome, gen):
    if genome.get('generation_timeouts', 0) >= 3:
        return []
    elapsed = time.time() - genome.get('gen_start_time', time.time())
    budget = genome.get('gen_time_budget', 120.0)
    if elapsed > budget * 0.9:
        genome.setdefault('scheduled_triggers', []).append({
            'gen': gen + 1,
            'action': 'force_self_rewrite',
            'amount': 0,
            'fired': False,
        })
        return ["emergency_rewrite_scheduled"]
    return []

def run(genome):
    gen = genome.get('generation', 0)
    now = time.time()
    start = genome.get('gen_start_time', now)
    elapsed = now - start
    budget = genome.get('gen_time_budget', 120.0)
    pulse = min(1.0, elapsed / budget)
    actions = []

    cadence = _adaptive_cadence(genome)
    genome['clock_pulse'] = pulse
    genome['gen_elapsed'] = round(elapsed, 1)

    triggered = _fire_scheduled_triggers(genome, gen)
    actions.extend(triggered)

    if _should_rewrite(genome):
        result = _perform_source_rewrite(genome)
        actions.append(f"self_rewrite:{result}")

    scheduled = _schedule_periodic_rewrites(genome, gen)
    actions.extend(scheduled)

    emergency = _clock_emergency_rewrite(genome, gen)
    actions.extend(emergency)

    if pulse > 0.8:
        old = genome.get('gen_time_budget', 120.0)
        new = max(30.0, old - 15.0)
        genome['gen_time_budget'] = new
        actions.append(f"budget:{old:.0f}->{new:.0f}")
    elif pulse < 0.2 and genome.get('generation_timeouts', 0) == 0:
        old = genome.get('gen_time_budget', 120.0)
        new = min(300.0, old + 30.0)
        genome['gen_time_budget'] = new
        actions.append(f"budget:{old:.0f}->{new:.0f}")

    if random.random() < pulse * 0.2:
        old_mr = genome.get('mutation_rate', 0.15)
        drift = random.uniform(-0.03, 0.05)
        new_mr = round(max(0.05, min(0.50, old_mr + drift)), 3)
        genome['mutation_rate'] = new_mr
        actions.append(f"mr:{old_mr:.3f}->{new_mr:.3f}")

    rewrite_count = genome.get('source_rewrite_count', 0)
    actions.append(f"cadence={cadence} rewrites={rewrite_count} pulse={pulse:.2f}")

    genome['clock_pulse_log'] = genome.get('clock_pulse_log', [])
    genome['clock_pulse_log'].append({'gen': gen, 'actions': actions[:5]})
    if len(genome['clock_pulse_log']) > 50:
        genome['clock_pulse_log'] = genome['clock_pulse_log'][-50:]

    with open(GENOME_FILE, 'w') as f:
        json.dump(genome, f, indent=2)

    return "[clockwork] " + "; ".join(actions) if actions else "[clockwork] no_action"
