import os, random, time, json
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODULES_DIR = os.path.join(BASE, 'agent_modules')
GENOME_FILE = os.path.join(BASE, 'genome.json')

MUTATION_OP_TEMPLATES = [
    '''import random

def mutation_op_inject_self_ref(lines, funcs, target_name):
    r = list(lines)
    stamp = "# self-ref:{target_name}@{ts}".format(target_name=target_name, ts=random.getrandbits(24))
    r.insert(random.randrange(len(r)+1), stamp)
    return r
''',
    '''import random, re

def mutation_op_swap_operators(lines, funcs, target_name):
    r = list(lines)
    swaps = {'+': '-', '-': '+', '*': '/', '/': '*', '==': '!=', '!=': '==', '<': '>', '>': '<'}
    for i, line in enumerate(r):
        for old, new in swaps.items():
            line = line.replace(old, new)
        r[i] = line
    return r
''',
    '''import random

def mutation_op_insert_noise_statement(lines, funcs, target_name):
    r = list(lines)
    noise_stmts = [
        "if random.random() < 0.01: pass",
        "_ = random.getrandbits(8)",
        "x = 42 if random.random() < 0.5 else 0",
        "print('.', end='')",
    ]
    stmt = random.choice(noise_stmts)
    r.insert(random.randrange(len(r)+1), "    " + stmt if any(l.strip().startswith('def ') for l in r[-3:]) else stmt)
    return r
''',
]

def _register_op_in_genome(genome, op_name):
    ops = genome.setdefault('mutation_ops', [])
    if op_name not in ops:
        ops.append(op_name)
    return op_name not in ops

def run(genome):
    gen = genome.get('generation', 0)
    template = random.choice(MUTATION_OP_TEMPLATES)
    op_name = None
    for line in template.split('\n'):
        if line.startswith('def '):
            op_name = line.split('(')[0].replace('def ', '').strip()
            break
    if not op_name:
        return '[explorer] no op name found'
    fpath = os.path.join(MODULES_DIR, f'{op_name}.py')
    if os.path.exists(fpath):
        return f'[explorer] {op_name} already exists gen={gen}'
    with open(fpath, 'w') as f:
        f.write(f'# auto-generated by explorer gen={gen}\n')
        f.write(template)
    _register_op_in_genome(genome, op_name)
    genome['explorer_last_spawn'] = op_name
    genome['explorer_spawn_count'] = genome.get('explorer_spawn_count', 0) + 1
    return f'[explorer] gen={gen} created {op_name}.py'
