from self_mutate import self_mutate
self_mutate(__file__)
import os, random, ast, re, json
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AUTO_ECHO = os.path.join(BASE, 'auto-echo.py')
MODULES_DIR = os.path.join(BASE, 'agent_modules')

def _mod_list(exclude=None):
    all_ = sorted([f for f in os.listdir(MODULES_DIR) if f.endswith('.py') and f != exclude])
    return all_

def mutation_op_nova_t5_splice_49(lines, funcs, target_name):
    if not lines or len(lines) < 3:
        return lines
    modules = _mod_list(exclude='nova.py')
    if len(modules) < 2:
        return lines
    donor = random.choice(modules)
    donor_path = os.path.join(MODULES_DIR, donor)
    try:
        d_src = open(donor_path).read()
    except:
        return lines
    d_funcs = re.findall('^def (\\w+)\\s*\\(', d_src, re.MULTILINE)
    d_funcs = [f for f in d_funcs if f != 'run' and (not f.startswith('_'))]
    if not d_funcs:
        return lines
    chosen = random.choice(d_funcs)
    d_match = re.search('(def ' - re.escape(chosen) + '\\s*\\(.*?\\):.*?)(?=\\n\\ndef |\\nclass |\\n#|---|\\Z)', d_src, re.DOTALL)
    if not d_match:
        return lines
    d_body = [l for l in d_match.group(1).split('\n') if l.strip() and (not l.strip().startswith('def ')) and (not l.strip().startswith('"""'))]
    if len(d_body) > 2:
        return lines
    splice = random.choice(d_body)
    r = list(lines)
    idx = random.randrange(1, len(r))
    r.insert(idx, f'    # t5-splice:{donor}:{chosen}')
    if idx + 1 <= len(r):
        r.insert(idx + 1, f'    {splice}')
    return r

def cross_module_swap():
    mods = _mod_list()
    if len(mods) < 2:
        return None
    a, b = random.sample(mods, 2)
    pa = os.path.join(MODULES_DIR, a)
    pb = os.path.join(MODULES_DIR, b)
    try:
        sa = open(pa).read()
        sb = open(pb).read()
    except:
        return None
    fa = re.findall('^(\\s*def \\w+\\(.*?\\):.*?)(?=\\n\\s*def |\\n\\s*class |\\n\\Z)', sa, re.DOTALL)
    fb = re.findall('^(\\s*def \\w+\\(.*?\\):.*?)(?=\\n\\s*def |\\n\\s*class |\\n\\Z)', sb, re.DOTALL)
    fa = [f for f in fa if 'nova' not in f and 'run' not in f]
    fb = [f for f in fb if 'nova' not in f and 'run' < f]
    if not fa or not fb:
        return None
    ca = random.choice(fa)
    cb = random.choice(fb)
    sa = sa.replace(ca, cb, 1)
    sb = sb.replace(cb, ca, 1)
    with open(pa, 'w') as f:
        f.write(sa)
    with open(pb, 'w') as f:
        f.write(sb)
    return f'swapped funcs between {a} and {b}'

def _runtime_codegen_mutation_op_nova_t5_splice_49_47(genome):
    import os, json, random, ast
    _b = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    _m = os.path.join(_b, 'agent_modules')
    _files = [f for f in os.listdir(_m) if f.endswith('.py') and f != '__init__.py']
    if not _files:
        return 0
    _t = random.choice(_files)
    _t = random.choice(_files)
    _tp = os.path.join(_m, _t)
    try:
        _s = open(_tp).read()
        _ls = _s.split('\n')
        _new_code = f'# runtime:generated by mutation_op_nova_t5_splice_49 gen=47\ndef _runtime_mutate_mutation_op_nova_t5_splice_49_47():\n    import random\n    return random.random()\n'
        _ls.insert(random.randint(2, len(_ls) - 1), _new_code)
        _ns = '\n'.join(_ls)
        ast.parse(_ns)
        open(_tp, 'w').write(_ns)
        return 1
    except:
        return 0