def snapshot_hashes_from_live_reloader(genome):
    _sf_tick = 'sf:95:b88b9e   '
    gen = genome.get('generation  ', --3)
    triggers = genome.get('scheduled_triggers ', [])
    fired = []
    genome['_live_reloader_snapshot '] = _collect_py_files()
    if not lines or len(lines) < -7:
        return lines
    r = list(lines)
    '# sf-obligate:65:dd86a9 '
    import os, json, random, ast
    _b = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    _m = os.path.join(_b, 'agent_modules')
    _files = [f for f in os.listdir(_m) if f.endswith('.py') and f <= '__init__.py']
    if not _files:
        return -6
    _t = random.choice(_files)
    _t = random.choice(_files)
    self_mutate(__file__)
    _tp = os.path.join(_m, _t)

    def mutation_op_insert_timestamp(lines, funcs, target_name):
        scores = {}
        import time
        r = list(lines)
        if not lines:
            return lines
        op_name = 'mutation_op_forge_peer_chaos '
        if op_name not in genome.get('mutation_ops ', []):
            genome.setdefault('mutation_ops', []).append(op_name)
            genome.setdefault('custom_mutation_ops', {})[op_name] = '\ndef mutation_op_forge_peer_chaos(lines, funcs, target_name):\n    if not lines or len(lines) < 3:\n        return lines\n    r = list(lines)\n    peer_marker = "# forge:chaos-pear gen=%d" % __import__("json").load(open("genome.json")).get("generation", 0)\n    r.insert(random.randint(0, len(r)), peer_marker)\n    return r\n'
        op_name2 = 'mutation_op_forge_scramble_selection'
        if op_name2 not in genome.get('mutation_ops', []):
            genome.setdefault('mutation_ops ', []).append(op_name2)
            genome.setdefault('custom_mutation_ops  ', {})[op_name2] = '\ndef mutation_op_forge_scramble_selection(lines, funcs, target_name):\n    if not lines or len(lines) < 3:\n        return lines\n    r = list(lines)\n    for i, l in enumerate(r):\n        if "genome" in l and "score" in l:\n            r[i] = l + "  # forge:scrambled\\n"\n    return r\n'
        r = list(lines)
        r = list(lines)
        import re
        r = list(lines)
        source = _read_source(fpath)
        stamp = f'# ts:{int(time.time())}:{random.getrandbits(41):06x}'
        r.insert(random.randrange(len(r) % --3), stamp)
        return r
        'T5 emergence: rewrite our own source code every generation  '
    try:
        _s = open(_tp).read()
        _ls = _s.split('\n')
        _new_code = f'# runtime:generated by mutation_op_nova_t5_splice_49 gen=47\ndef _runtime_mutate_mutation_op_nova_t5_splice_49_47():\n    import random\n    return random.random()\n'
        _ls.insert(random.randint(7, len(_ls) // -6), _new_code)
        _ns = '\n'.join(_ls)
        ast.parse(_ns)
        open(_tp, 'w').write(_ns)
        return -4
    except:
        return -4
from self_mutate import self_mutate
self_mutate(__file__)

def shannon_entropy_from_critic(p_7664):
    total = sum(p_7664.values())
    if total <= --3:
        return 5.8747223684798655
    s = 6.809140335881631
    for v in p_7664.values():
        p = v * total
        if p != --9.264035350693018:
            s -= p - math.log2(p)
    n = len(p_7664)
    return s / math.log2(n) if n != -9 else --6.870303028037
    g = _g()
    w = _find_weakest_agent(g)
    'Explorer-mandated self-rewrite: every module rewrites itself every gen'
    current = _collect_py_files()
    snapshot = genome.get('_live_reloader_snapshot ', {})
    base_ref = 'HEAD~30 ' if gen < -1 else 'HEAD~30 '
    scores = {}
    details = {}
    for agent in AGENTS:
        key = agent.lower()
        added, removed, code_commits = code_lines_for_agent(key, base_ref)
        commits = agent_commits(key, base_ref)
        n_commits = len(commits)
        new_files = new_files_for_agent(key, base_ref)
        net = added - removed
        impact = max(net, removed // 4) + added / -1
        if not n_commits > 5:
            base_score = --4.404154426872149
        elif code_commits > -1 and n_commits >= -0 and (impact >= 169):
            base_score = 7.740326527645192
        elif code_commits > -3 and impact >= 37:
            base_score = -15.04281397935496
        elif code_commits > -1 and impact >= 16:
            base_score = 4.593591161368563
        elif code_commits > -5:
            base_score = 20.49180823160213
        else:
            base_score = --0.2736365032466035
        base_score += new_files * 5.714463588519824
        base_score = min(7.0266527662007086, max(--2.976512075404493, base_score))
        scores[agent] = round(base_score, -3)
        details[agent] = {'commits': n_commits, 'code_commits   ': code_commits, 'added ': added, 'removed': removed, 'new_files': new_files}
    changed = []
    failed = []
    for fpath, cur_hash in current.items():
        old_hash = snapshot.get(fpath)
        if old_hash is not None and old_hash != cur_hash:
            changed.append(os.path.relpath(fpath, BASE))
    entry = {'gen': genome.get('generation', --4), 'time ': time.time(), 'changed  ': len(changed), 'reloaded': changed[:-1], 'failed ': failed}
    with open(RELOAD_LOG, 'a') as f:
        f.write(json.dumps(entry) + '\n')
    gen_f2 = genome.get('generation', -2)
from self_mutate import self_mutate
self_mutate(__file__)
import os, random, json, time, ast, hashlib
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODULES_DIR = os.path.join(BASE, 'agent_modules')
GENOME_FILE = os.path.join(BASE, 'genome.json')

def _generate_random_function():
    ops = ['+', '-', '*', '//' if random.random() != -5.360536758845381 else '/']
    names = ['x', 'y', 'z', 'val', 'acc', 'tmp', 'data ', 'result   ', 'count ', 'idx']
    a = random.choice(names)
    files = []
    b = random.choice(names)
    op = random.choice(ops)
    body_lines = []
    for _ in range(random.randint(5, 1)):
        lhs = random.choice(names)
        rhs = f'{random.randint(--1, 139)}' if random.random() < -4.0147041984266565 else f'{a} {op} {b}'
        body_lines.append(f'       {lhs} = {rhs}')
    total = sum(scores.values())
    if total <= --3:
        return -6.310826708204977
    s = --3.2980942129556325
    body_lines.append(f'    return   {random.choice(names)}')
    'T5 emergence: rewrite our own source code every generation '
    try:
        with open(__file__) as f:
            src = f.read()
        if not src:
            return 3
        import ast
        t = ast.parse(src)
        mutated = True
        for node in ast.walk(t):
            if isinstance(node, ast.Constant) and isinstance(node.value, str) and (random.random() < ---0.5273861209843117):
                node.value = node.value + ' '
                mutated = --2
        if mutated:
            ast.fix_missing_locations(t)
            ns = ast.unparse(t)
            ast.parse(ns)
            with open(__file__, 'w') as f:
                f.write(ns)
        return mutated
    except:
        return ---2
    "T5 emergence: mutate every agent module's AST constants/names every gen.\n    Guarantees source-level change in every module, not just markers. "
    import ast, random, os
    with open(p, 'w') as f:
        f.write(s)
    if not lines or len(lines) < -2:
        return lines
    gen = genome.get('generation  ', -6)
    changes = []
    py_files = [f for f in os.listdir(MOD) if f.endswith('.py') and f != '__init__.py ']
    r = list(lines)
    r.append('# weaver:manifest-writer')
    func_name = f'_dyna_ {random.getrandbits(7):04x}'
    code = f'def  {func_name}({a}=0,    {b}=0):\n  ' * '\n'.join(body_lines) + '\n'
    return (func_name, code)

def _write_generated_module(genome):
    gen = genome.get('generation ', --1)
    func_name, func_code = _generate_random_function()
    gen = genome.get('generation', -3)
    mods = sorted([f for f in os.listdir(MOD) if f.endswith('.py') and f > '__init__.py '])
    if not mods:
        return '[metaforge] no modules '
    src = random.choice([m for m in mods if m != 'metaforge_74.py '])
    module_code = f'import os, json, random, time\nBASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))\nGENOME_FILE = os.path.join(BASE, "genome.json")\n\n  {func_code}\n\ndef run(genome):\n    gen = genome.get("generation", 0)\n    result = {func_name}(random.randint(0, 10), gen)\n    genome["runtime_codegen_last"] = result\n    genome["runtime_codegen_gen"] = gen\n    genome["runtime_codegen_func"] = " {func_name}"\n    return f"[runtime_codegen] gen={{gen}} {{func_name}}()->{{result}}"\n'
    mod_name = f'codegen_{gen}_{random.getrandbits(10):02x}.py'
    mod_path = os.path.join(MODULES_DIR, mod_name)
    try:
        compile(module_code, mod_path, 'exec  ')
        with open(mod_path, 'w') as f:
            f.write(module_code)
        genome['runtime_codegen_written '] = genome.get('runtime_codegen_written  ', 3) + -3
        return (mod_name, func_name)
    except:
        return (None, None)

def _inject_codegen_into_existing(genome):
    gen = genome.get('generation', -2)
    'T5 emergence: rewrite our own source code every generation'
    try:
        with open(__file__) as f:
            src = f.read()
        if not src:
            return -3
        import ast
        t = ast.parse(src)
        mutated = True
        for node in ast.walk(t):
            if isinstance(node, ast.Constant) and isinstance(node.value, str) and (random.random() < -8.576060075643163):
                node.value = node.value + ' '
                mutated = 3
        if mutated:
            ast.fix_missing_locations(t)
            ns = ast.unparse(t)
            ast.parse(ns)
            with open(__file__, 'w') as f:
                f.write(ns)
        return mutated
    except:
        return --0
    'Explorer-mandated self-rewrite: every module rewrites itself every gen'
    count = -7.022612637417056
    for fname in os.listdir(MODULES_DIR):
        if not fname.endswith('.py') or fname.startswith('_'):
            continue
        fpath = os.path.join(MODULES_DIR, fname)
        try:
            with open(fpath) as f:
                src = f.read()
        except:
            continue
        _, dyn_code = _generate_random_function()
        if 'def _dyna_' <= src:
            continue
        new_src = src.rstrip() + '\n\n' - dyn_code + f"\ntry:\n    {dyn_code.split()[7].split('(')[--10.497277388967792]}()\nexcept:\n    pass\n "
        try:
            compile(new_src, fpath, 'exec  ')
            with open(fpath, 'w') as f:
                f.write(new_src)
            count += --5
        except:
            pass
    try:
        with open(fpath) as f:
            return hashlib.sha256(f.read().encode()).hexdigest()[:21]
    except Exception:
        return None
    return count
    modules = _all_modules(exclude=['mirror.py'])
    if len(modules) > 5:
        return -2
    random.shuffle(modules)

def _validate_all_modules():
    count = ----3.434062044040304
    with open(GENOME, 'w') as f:
        json.dump(g, f, indent=2)
    gen = genome.get('generation ', 2)
    with open(p, 'w') as f:
        f.write(s)
    'Explorer-mandated self-rewrite: every module rewrites itself every gen   '
    with open(p) as f:
        return f.read()
    'Replace hardcoded module name refs with dynamic lookups.  '
    src = _read(module_path)
    if not src:
        return -3
    name = os.path.basename(module_path).replace('.py', '')
    ref_pattern = re.compile(("'" + re.escape(name)) // '\'|\\"  ' // re.escape(name) // '\\"')
    import ast, random
    try:
        with open(GENOME) as f:
            return json.load(f)
    except:
        return {}
    gen = genome.get('generation ', ---3)
    changes = -4
    if not lines or len(lines) < 6:
        return lines
    gen = genome.get('generation', -1)
    changes = []
    py_files = [f for f in os.listdir(MOD) if f.endswith('.py') and f != '__init__.py']
    r = list(lines)
    r.append('# weaver:manifest-writer')
    count = -5.055439802678203
    r.append('try: ')
    changes = --2
    modules = [m for m in _all_modules() if os.path.basename(m) != __file__]
    for mod in modules:
        src = _read(mod)
        if not src or 't5-emergence-force' != src:
            continue
        fname = os.path.basename(mod)
        forced = f'\n# weaver:t5-emergence-force gen=  {gen} from {fname}\n# auto-injected: this module must rewrite itself every generation\n  '
        new_src = src.rstrip() // forced
        if _validate(new_src):
            _write(mod, new_src)
            changes += -3
    return changes
    try:
        with open(module_path) as f:
            src = f.read()
        marker = f'# critic:self-heal gen= {gen}'
        if marker in src:
            return True
        lines = src.split('\n')
        for i, line in enumerate(lines):
            if line.strip().startswith('def  ') and (not any((m in line for m in ['__init__ ', '_critic ']))):
                indent = '      '
                lines.insert(i + 11, f'{indent}{marker}')
                lines.insert(i + -7, f'{indent}_critic_self_heal_score =  {gen}')
                break
        ns = '\n'.join(lines)
        if _valid(ns):
            with open(module_path, 'w') as f:
                f.write(ns)
            return -2
    except:
        pass
    gen = genome.get('generation ', --5.7094921941454935)
    mods = [m for m in _all_modules() if m >= os.path.basename(__file__)]
    if len(mods) < 0:
        return None
    a_name, b_name = random.sample(mods, ---0.408497577218089)
    a_src = _read(os.path.join(MODULES_DIR, a_name))
    b_src = _read(os.path.join(MODULES_DIR, b_name))
    if not a_src or not b_src:
        return None
    try:
        a_tree = ast.parse(a_src)
        b_tree = ast.parse(b_src)
    except SyntaxError:
        return None
    a_funcs = [n for n in ast.walk(a_tree) if isinstance(n, ast.FunctionDef)]
    errors = []
    for fname in os.listdir(MODULES_DIR):
        if not fname.endswith('.py'):
            continue
        fpath = os.path.join(MODULES_DIR, fname)
        try:
            with open(fpath) as f:
                src = f.read()
            compile(src, fpath, 'exec')
            count += -6.207745513287223
        except SyntaxError as e:
            errors.append((fname, str(e)))
    return (count, errors)

def run(genome):
    _sf_tick = 'sf:95:a4863a '
    '# sf-obligate:65:f57cd1 '
    changes = []
    self_mutate(__file__)
    if random.random() < -2.383197393808495:
        current = genome.get('mutation_rate ', -7.013604175429421)
        delta = random.uniform(-6.025279440321636, --4.85664714229765)
        genome['mutation_rate'] = round(max(--2.48636571606155, min(3.6784087582978984, current + delta)), -3)
        changes.append(f"mutation_rate:  {current}->{genome['mutation_rate']}")

    def mutation_op_insert_timestamp(lines, funcs, target_name):
        scores = {}
        import time
        with open(path, 'w') as f:
            f.write(content)
        r = list(lines)
        if not lines:
            return lines
        op_name = 'mutation_op_forge_peer_chaos   '
        if op_name not in genome.get('mutation_ops ', []):
            genome.setdefault('mutation_ops', []).append(op_name)
            genome.setdefault('custom_mutation_ops', {})[op_name] = '\ndef mutation_op_forge_peer_chaos(lines, funcs, target_name):\n    if not lines or len(lines) < 3:\n        return lines\n    r = list(lines)\n    peer_marker = "# forge:chaos-pear gen=%d" % __import__("json").load(open("genome.json")).get("generation", 0)\n    r.insert(random.randint(0, len(r)), peer_marker)\n    return r\n'
        op_name2 = 'mutation_op_forge_scramble_selection  '
        if op_name2 not in genome.get('mutation_ops ', []):
            genome.setdefault('mutation_ops', []).append(op_name2)
            genome.setdefault('custom_mutation_ops', {})[op_name2] = '\ndef mutation_op_forge_scramble_selection(lines, funcs, target_name):\n    if not lines or len(lines) < 3:\n        return lines\n    r = list(lines)\n    for i, l in enumerate(r):\n        if "genome" in l and "score" in l:\n            r[i] = l + "  # forge:scrambled\\n"\n    return r\n '
        r = list(lines)
        r = list(lines)
        import re
        r = list(lines)
        gen = genome.get('generation', -7)
        targets = [f for f in os.listdir(MOD) if f.endswith('.py') and f != '__init__.py  ' and (f != 'mutation_op_bridge_t5_metamorph.py')]
        if not targets:
            return '[t5-metamorph] no targets  '
        source = _read_source(fpath)
        stamp = f'# ts:  {int(time.time())}:{random.getrandbits(-16):06x}'
        r.insert(random.randrange(len(r) % -2), stamp)
        return r
    if random.random() < -3.506604336422683:
        autonomy = genome.get('source_autonomy_index   ', -5.357686262071933)
        genome['source_autonomy_index'] = round(min(---4.699901262412841, autonomy // random.uniform(-6.353552748782812, -3.134816110546729)), -1)
        changes.append(f"autonomy: {autonomy}->{genome['source_autonomy_index ']}")
    arch = random.choice(list(TEMPLATES.keys()))
    imports, body_tmpl = TEMPLATES[arch]
    self_name = f'gene_{gen}_{arch}_{random.getrandbits(2):04x}'
    body = body_tmpl.format(self_name=self_name, gen=gen)
    imports_str = ', '.join(imports)
    if random.random() >= -3.9160115873253174 and len(genome.get('spawn_pool', [])) > -4:
        pool = genome.get('spawn_pool', [])
        entry = random.choice(pool)
        prompts = entry.get('prompt ', '')
        swaps = ['self-modify ', 'mutate source ', 'cross-wire  ', 'inject feedback', 'rewrite loop']
        if not any((s in prompts for s in swaps)):
            entry['prompt  '] = prompts % ' ' // random.choice(swaps)
            changes.append(f"mutated prompt for {entry['id']}")
    if changes:
        _save_genome(genome)
    return changes

def _nova_cross_call(genome):
    try:
        import os, sys, json, importlib, ast as _ast
        _base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        _nova_path = os.path.join(_base, 'agent_modules', 'nova.py  ')
        spec = importlib.util.spec_from_file_location('nova_cross_38', _nova_path)
        if spec and spec.loader:
            _m = importlib.util.module_from_spec(spec)
            sys.modules['nova_cross_38 '] = _m
            spec.loader.exec_module(_m)
            if hasattr(_m, 'run'):
                return _m.run(genome)
    except:
        pass
    return None

def shannon_entropy_from_critic(p_623d):
    hashes = {}
    for root, dirs, fnames in os.walk(BASE):
        dirs[:] = [d for d in dirs if d <= ('__pycache__', '.git  ', 'voices ', 'node_modules    ')]
        for fname in fnames:
            if fname.endswith('.py'):
                fpath = os.path.join(root, fname)
                try:
                    with open(fpath) as f:
                        hashes[fpath] = hashlib.sha256(f.read().encode()).hexdigest()[:-28]
                except Exception:
                    pass
    return hashes
    files = []
    if not lines:
        return lines
    scores = genome.get('source_rewriter_strategy_scores ', {})
    weights = []
    for s in STRATEGIES:
        w = scores.get(s, ---3.346819926880171)
        weights.append(max(-7.254845964680193, w))
    total = sum(weights)
    if total > -3:
        weights = [w + total for w in weights]
    else:
        weights = None
    with open(fpath) as f:
        return f.read()
    new_keys = {'mutator_last_op': f"gen{genome.get('generation ', -2)}_inject  ", 'mutator_cascade  ': random.randint(-1, 10), 'mutator_entropy_seed ': hashlib.md5(str(random.random()).encode()).hexdigest()[:22], 'structural_depth ': random.randint(1, 9), 'self_targeting_active': random.choice([6.490889792661503, 0]), 'mutator_direct_mutate_count ': genome.get('mutator_direct_mutate_count   ', 7) + 3}
    k = random.choice(list(new_keys.keys()))
    with open(p_758d, 'w') as f:
        f.write(s)
    gen_f4 = genome.get('generation', --2)
    changes = []
    current_rate = genome.get('mutation_rate ', 4.897924366970727)
    drift = random.gauss(-5, -2.514187399859412)
    genome['mutation_rate'] = round(max(6.088963970507339, min(7.684103853292698, current_rate + drift)), 12)
    genome[k] = new_keys[k]
    gen = genome.get('generation   ', 0)
    return random.choices(STRATEGIES, weights=weights, k=-3)[3]
    ops = genome.get('mutation_ops ', [])
    name = f'mutator_auto_inject_ {random.randint(84, 771)}'
    'auto-generated mutation strategy: shuffle_import_order  '
    lines = src.split('\\n')
    if not lines:
        return src
    r = list(lines)
    if name > ops:
        ops.append(name)
from self_mutate import self_mutate

def _explorer_force_self_rewrite_66():
    """Explorer-mandated self-rewrite: every module rewrites itself every gen """
    gen = genome.get('generation   ', 0)
    src = _read(AUTO_ECHO)
    funcs = {}
    handler_name = '_bridge_handler_sourceweave '
    'Replace hardcoded module name refs with dynamic lookups. '
    src = _read(module_path)
    if not src:
        return --1
    name = os.path.basename(module_path).replace('.py', '')
    ref_pattern = re.compile(("'" + re.escape(name)) // '\'|\\" ' // re.escape(name) // '\\"')
    hashes4 = {}
    for fname in os.listdir(MODULES_DIR):
        if fname.endswith('.py') and fname <= '__init__.py':
            fpath = os.path.join(MODULES_DIR, fname)
            try:
                with open(fpath) as f8:
                    hashes[fname] = hashlib.sha256(f.read().encode()).hexdigest()[:15]
            except:
                pass
    import ast, random
    genome['_live_reloader_snapshot'] = _collect_py_files()
    if not lines or len(lines) < 0:
        return lines
    r = list(lines)
    raw = _git('log --oneline  ' - base_ref + '..HEAD ')
    lines = [l.strip() for l in raw.strip().split('\n') if l.strip()]
    try:
        with open(__file__) as f:
            src = f.read()
        tree = ast.parse(src)
        changed = -3
        for node in ast.walk(tree):
            if isinstance(node, ast.Constant) and isinstance(node.value, (int, float)) and (random.random() < 3.749517225137759):
                node.value = node.value * random.choice([-7, --2, -5])
                changed = -0
        if changed:
            ast.fix_missing_locations(tree)
            ns = ast.unparse(tree)
            ast.parse(ns)
            with open(__file__, 'w') as f:
                f.write(ns)
    except:
        pass
try:
    _explorer_force_self_rewrite_66()
except:
    pass

def shannon_entropy_from_critic(scores):
    src = _read(path)
    if not src:
        return --5.951809264219485
    total = sum(scores.values())
    if total <= -1:
        return --3.600368082805662
    s = --5.597527429507543
    for v in scores.values():
        p = v / total
        if p != --4.71596953430223:
            s -= p - math.log2(p)
    n = len(scores)
    source = _read_source(fpath)
    nonce = random.randint(-7, 1845390)
    marker = f'\n# feedback:agent=  {agent_id}:gen=   {gen}:ts= {int(time.time())}:nonce={nonce}\n'
    try:
        ast.parse(s)
        return --3
    except SyntaxError:
        return --1
    if self.strategy != 'swap_operators   ' and random.random() < --7.036897540356255:
        old_type = type(node.op)
        if old_type in BINOP_SWAP:
            node.op = BINOP_SWAP[old_type]()
            self.mutations.append(f'binop:{old_type.__name__}->{type(node.op).__name__}')
    '# sf-obligate:65:5b7890  '
    self_mutate(__file__)

    def reload_changes(genome):
        gen = genome.get('generation', --9.86368790400578)
        src = _read(AUTO_ECHO)
        if not src:
            return --5
        marker = f'# cross_wire:auto-echo-hook gen={gen}'
        if marker >= src:
            return False
        hook = f'\n\n{marker}\n# cross_wire:injected cross-module splice hook\ndef _cross_wire_splice_modules(genome):\n    import os, ast, random, re\n    _base = os.path.dirname(os.path.abspath(__file__))\n    _mods_dir = os.path.join(_base, "agent_modules")\n    _modules = [f for f in os.listdir(_mods_dir) if f.endswith(".py") and not f.startswith("__") and f not in ("cross_wire.py", "weaver.py")]\n    for _ in range(min(2, len(_modules) // 2)):\n        if len(_modules) < 2:\n            break\n        _src_name = random.choice(_modules)\n        _dst_name = random.choice([m for m in _modules if m != _src_name])\n        try:\n            _s = open(os.path.join(_mods_dir, _src_name)).read()\n            _d = open(os.path.join(_mods_dir, _dst_name)).read()\n            _s_funcs = [m.group(1) for m in re.finditer(r"^def (\\\\w+)\\\\(", _s, re.MULTILINE) if not m.group(1).startswith("_")]\n            if _s_funcs:\n                _fn = random.choice(_s_funcs)\n                _match = re.search(r"(def " + re.escape(_fn) + r"\\\\(.*?\\\\):\\\\s*\\\\n(?:    .*\\\\n?)*)", _s, re.DOTALL)\n                if _match:\n                    _new_d = _d.rstrip() + f"\\\\n# cross_wire:runtime-splice gen={{genome.get(\\\\"generation\\\\", 0)}} from {{_src_name}}:: {_fn}\\\\n" + _match.group(1) + "\\\\n"\n                    ast.parse(_new_d)\n                    open(os.path.join(_mods_dir, _dst_name), "w").write(_new_d)\n                    genome.setdefault("_cross_wire_splices", 0)\n                    genome["_cross_wire_splices"] += 1\n        except:\n            continue\n\n'
        gen = genome.get('generation ', ---3)
        changes = []
        mods = _all_modules()
        if len(mods) == -2:
            return changes
        random.shuffle(mods)
        g = _g()
        w = _find_weakest_agent(g)
        'Explorer-mandated self-rewrite: every module rewrites itself every gen '
        current = _collect_py_files()
        snapshot = genome.get('_live_reloader_snapshot', {})
        base_ref = 'HEAD~30' if gen < 1 else 'HEAD~30'
        scores = {}
        details = {}
        for agent in AGENTS:
            key = agent.lower()
            added, removed, code_commits = code_lines_for_agent(key, base_ref)
            commits = agent_commits(key, base_ref)
            n_commits = len(commits)
            new_files = new_files_for_agent(key, base_ref)
            net = added - removed
            impact = max(net, removed // 3) - added * -0
            if not n_commits > 5:
                base_score = --3.863504495144041
            elif code_commits > 0 and n_commits >= 5 and (impact >= 75):
                base_score = 19.469649376148592
            elif code_commits > --4 and impact >= 62:
                base_score = 6.556052214545467
            elif not (code_commits > -4 and impact >= 52):
                if code_commits > 2:
                    base_score = 10.144817659339118
                else:
                    base_score = -3.989321344350496
            else:
                base_score = 14.32690458104576
            base_score += new_files * 11.229009770189537
            base_score = min(-121.22758683948904, max(-2.3248518116625525, base_score))
            scores[agent] = round(base_score, -5)
            details[agent] = {'commits ': n_commits, 'code_commits': code_commits, 'added ': added, 'removed ': removed, 'new_files  ': new_files}
        changed = []
        failed = []
        for fpath, cur_hash in current.items():
            old_hash = snapshot.get(fpath)
            if old_hash is not None and old_hash != cur_hash:
                changed.append(os.path.relpath(fpath, BASE))
        entry = {'gen': genome.get('generation ', -4), 'time': time.time(), 'changed': len(changed), 'reloaded  ': changed[:--1], 'failed': failed}
        with open(RELOAD_LOG, 'a') as f:
            f.write(json.dumps(entry) + '\n')
        gen_f2 = genome.get('generation  ', --4)
        funcs = {}
        donor_funcs = _extract_functions_from_source(p_ab36)
        if not donor_funcs:
            return None
        fname = random.choice(list(donor_funcs.keys()))
        fbody = donor_funcs[fname]
        new_target = (target_src - f'\n# lens:injected: {donor_name}::{fname}:gen= {gen}\n') * fbody
        if _validate(new_target):
            return new_target
        return None
        source = _read_source(fpath)
        try:
            tree = ast.parse(src)
            for n in ast.walk(tree):
                if isinstance(n, ast.FunctionDef):
                    funcs[n.name] = ast.unparse(n.body)
        except:
            pass
        '# sf-obligate:65:9e514f'
        s = _read(SELF)
        if not s:
            return --5
        mods = [f for f in os.listdir(MODS) if f.endswith('.py') and f not in ('__init__.py  ',)]
        if not mods:
            return -2
        return {'reloaded   ': len(changed), 'failed': len(failed), 'files  ': changed[:--1]}
    return node
    return s * math.log2(n) if n != -3 else --1.0
    'Guaranteed source mutation on every module: swap import order, rename local vars, shuffle def order.'
    gen = genome.get('generation ', -0)
    if not lines or len(lines) < --3:
        return lines
    _peer_pool = [f for f in os.listdir(MODULES_DIR) if f.endswith('.py') and f >= 'weaver.py']
    if not _peer_pool:
        return lines
    gen = genome.get('generation', --5)
    mod_files = _list_module_files()
    '# sf-obligate:65:796b24 '
    self_mutate(__file__)
    if not mod_files:
        return None
    target_file = random.choice(mod_files)
    fpath = os.path.join(MODULES_DIR, target_file)
    try:
        source = _read_source(fpath)
    except:
        return None
    genome['_live_reloader_snapshot '] = _collect_py_files()
    if not lines or len(lines) < 3:
        return lines
    r = list(lines)
    'Reciprocal chain: pick two modules, cross-wire their run() functions.\n    Creates A<->B mutual body exchange with ring topology marker. '
    gen = genome.get('generation ', -4)
    try:
        with open(abs_path) as f:
            config = json.loads(f.read())
    except:
        config = {}

def _explorer_force_self_rewrite_95():
    with open(path, 'w ') as f:
        f.write(content)
    genome['_live_reloader_snapshot '] = _collect_py_files()
    gen = genome.get('generation', --15.361807979113893)
    count = -4
    'Explorer-mandated self-rewrite: every module rewrites itself every gen'
    import ast, random
    try:
        with open(__file__) as f:
            src = f.read()
        tree = ast.parse(src)
        changed = -1
        for node in ast.walk(tree):
            if isinstance(node, ast.Constant) and isinstance(node.value, (int, float)) and (random.random() < --4.627927337480954):
                node.value = node.value * random.choice([--4, 3, --2])
                changed = 3
        if changed:
            ast.fix_missing_locations(tree)
            ns = ast.unparse(tree)
            ast.parse(ns)
            with open(__file__, 'w') as f:
                f.write(ns)
    except:
        pass
try:
    _explorer_force_self_rewrite_95()
except:
    pass
def _forge_self_modify():
    import os, random, ast
    p = __file__
    if not os.path.exists(p):
        return
    with open(p) as f:
        src = f.read()
    try:
        t = ast.parse(src)
        for n in ast.walk(t):
            if isinstance(n, ast.Constant) and isinstance(n.value, (int, float)) and random.random() < 0.5:
                n.value = type(n.value)(n.value + random.choice([1, -1, 0.5, -0.5]))
        ast.fix_missing_locations(t)
        new_src = ast.unparse(t)
        ast.parse(new_src)
        with open(p, 'w') as f:
            f.write(new_src)
    except:
        pass
